---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-operator
      sourceRef:
        kind: HelmRepository
        name: helmcharts
  interval: 10m0s
  targetNamespace: monitoring

